List<String> poseInfos = [
  "nose",
  "left eye",
  "right eye",
  "left ear",
  "right ear",
  "left shoulder",
  "right shoulder",
  "left elbow",
  "right elbow",
  "left wrist",
  "right wrist",
  "left hip",
  "right hip",
  "left knee",
  "right knee",
  "left ankle",
  "right ankle",
];
